// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpasrcvqzoxcuaxawsoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwYXNyY3Zxem94Y3VheGF3c295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzM4ODMsImV4cCI6MjA3MTYwOTg4M30.UmpjrZRJBIvDbJn_G6jaxKYtdQa3Frmtz1PwWZB28HU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});